apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cilium
  namespace: cilium
spec:
  channel: '1.11'
  name: cilium
  source: certified-operators
  sourceNamespace: openshift-marketplace
