apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - frontend-ingress.yaml

patchesStrategicMerge:
  # frontend - remove the frontend-external Service
    - |-
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend-external
      $patch: delete
