apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/GoogleCloudPlatform/microservices-demo/kustomize

components:
  # Remove Service frontend-external and replace it with Ingress
  - components/ingress
  # Enable tracing
  - components/tracing
