apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium-demo

resources:
  - frontend-ingress.yaml

helmChartInflationGenerator:
  - chartName: opentelemetry-demo
    chartRepoUrl: https://open-telemetry.github.io/opentelemetry-helm-charts
    chartVersion: 0.2.5
    releaseName: cilium-demo
    values: opentelemetry-demo-values.yaml
