observability:
  otelcol:
    enabled: false
  jaeger:
    enabled: false

default:
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: 'metadata.labels[''app.kubernetes.io/component'']'
    - name: OTEL_K8S_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OTEL_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: OTEL_K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_K8S_POD_NAME)
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://cluster-collector-collector.cilium:55690

components:
  adService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  cartService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  checkoutService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  currencyService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  emailService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  featureflagService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>,<Ingress/50053/TCP/HTTP>

  frontend:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  loadgenerator:
    podAnnotations:
      io.cilium.proxy-visibility: <Egress/8080/TCP/HTTP>

  paymentService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  productCatalogService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  recommendationService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>

  shippingService:
    podAnnotations:
      io.cilium.proxy-visibility: <Ingress/8080/TCP/HTTP>
