apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-inmemory
  namespace: tracing-system
spec:
  strategy: allInOne
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
